version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      cron: 0 0 1 * *
    open-pull-requests-limit: 10
    groups:
      dependencies:
        patterns:
        - "*"
    labels:
      - "dependencies"
    target-branch: "master"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      cron: 0 0 1 * *
    open-pull-requests-limit: 5
    commit-message:
      prefix: "[workflow]"
    labels:
      - "dependencies"
    target-branch: "master"
